blueprint:
  name: "[Blueprint] Doorbell Ring and Unlock Action with Cooldown"
  description: Sends a notification when the doorbell is rung and handles an unlock action. It includes a cooldown to prevent spamming of notifications.
  domain: automation
  source_url: https://wectrl.net
  author: wectrl.net
  input:
    triggers:
      name: Additional / Custom triggers
      description: The triggers that make the doorbell ring
      default:
        - platform: event
          event_type: mobile_app_notification_action
          event_data:
            action: UNLOCK_DOOR
      selector:
        trigger:
    unlock_action_name:
      name: Unlock action name
      description: The action name used to unlock the door
      default: UNLOCK_DOOR
    lock_entity:
      name: Door lock entity
      description: The entity for the lock that will be unlocked
      default: []
      selector:
        entity:
          domain: lock
    camera_entity:
      name: Camera entity
      description: The entity of the camera to show in the notification
      selector:
        entity:
          domain: camera
    timer_entity:
      name: Timer entity
      description: The entity for the timer to prevent notification spam
      selector:
        entity:
          domain: timer
    click_url:
      name: Click URL
      description: Where the user will be taken if they tap the notification. (ie. /lovelace/kitchen)
      default: "/lovelace/ROOM"
      selector:
        text:
    title:
      name: Notification Title
      description: The title of the notification. 
      default: "Front Door Ringing"
      selector:
        text:
    message:
      name: Notification Message
      description: The message of the notification.
      default: "Someone is at the front door!"
      selector:
        text:
    notification_icon_warning:
      name: Notification Icon (Android Only)
      description: The icon that is shown when the issue is reported. (ie. mdi:fridge-alert)
      default: "alert"
      selector:
        select:
          options:
            - alert
            - alert-circle
            - door
            - door-open
            - motion-sensor
            - fridge
            - fridge-alert
            - home
            - home-alert
            - home-assistant
    notification_color:
      name: Notification Color (Android Only)
      description: The color of the notification.
      default: "red"
      selector:
        select:
          options:
            - "red"
            - "orange"
            - "yellow"
            - "green"
            - "blue"
            - "purple"
    interruption_level:
      name: Interruption Level (iOS Only)
      description: The intrusiveness of the notification recieved. This also determines whether the notification will be delivered while the device is in a focus mode.
      default: "active"
      selector:
        select:
          options:
            - passive
            - active
            - time-sensitive
            - critical
    notification_action:
      name: Notification Action
      description: Action to run when the bell is rung
      default: [] # Optional
      selector:
        action: {}

variables:
  unlock_action_name: !input unlock_action_name
  notification_icon_warning: !input notification_icon_warning
  lock_entity: !input lock_entity

trigger: !input triggers

condition: []

action:
  - if:
      - condition: template
        value_template: "{{ trigger.platform == 'event' and trigger.event.data.action == unlock_action_name and lock_entity }}"
    then:
      - service: lock.unlock
        entity_id: !input lock_entity
    else:
      - if:
          - condition: state
            entity_id: !input timer_entity
            state: 'idle'
        then:
          - parallel:
            - service: timer.start
              entity_id: !input timer_entity
              data:
                duration: "00:00:30"
            - sequence:
              - alias: "Run the Custom Notification actions"
                choose: []
                default: !input notification_action
            - service: notify.notify
              data:
                message: !input message
                title: !input title
                data:
                  entity_id: !input camera_entity
                  clickAction: !input click_url
                  url: !input click_url
                  color: !input notification_color
                  notification_icon: 'mdi:{{ notification_icon_warning }}'
                  push:
                    interruption-level: !input interruption_level
                  actions:
                    - action: !input unlock_action_name
                      title: Unlock Door
                      icon: "sfsymbols:lock.open.fill"
                      authenticationRequired: true
mode: parallel
