blueprint:
  name: "[Blueprint] Notify On State Change"
  description: Sends a notification when the state of a specified sensor changes.
  domain: automation
  source_url: https://wectrl.net
  input:
    target_sensor:
      name: Sensor
      description: Select the sensor you want to monitor for state changes.
      selector:
        entity:
          domain: 
            - sensor
            - binary_sensor
    notify_service:
      name: Notification Service
      description: Select the notification service you want to use.
      default: notify.notify
      selector:
        text:
    notification_text:
      name: Notification Text
      description: Customize the message text for the notification.
      default: "The {{ trigger.to_state.name }} changed to {{ state_translated(trigger.to_state.entity_id) }}!"
      selector:
        text:
    notification_title:
      name: Notification Title
      description: Customize the title text for the notification.
      default: "State change"
      selector:
        text:
    exclude_unknown_unavailable:
      name: Exclude Unknown/Unavailable States
      description: Whether to exclude state changes to or from 'unknown' and 'unavailable'.
      default: true
      selector:
        boolean:

trigger:
  - platform: state
    entity_id: !input 'target_sensor'

variables:
    exclude_unknown_unavailable_boolcfg: input.exclude_unknown_unavailable

condition:
  - condition: template
    value_template: "{{ trigger.from_state != trigger.to_state }}"
  - condition: template
    value_template: >
      {% if not (exclude_unknown_unavailable_boolcfg) %}
        true
      {% else %}
        {{ trigger.from_state.state not in ['unknown', 'unavailable'] }}
      {% endif %}

action:
  - service: !input 'notify_service'
    data:
      title: !input 'notification_title'
      message: !input 'notification_text'

mode: single